#!/bin/bash

root=$(dirname $(dirname $0))
dist="$root/agent"

JVM_OPTS=${JVM_OPTS:-""}

MVN=${MVN:-mvn}
MVN_OPTS=${MVN_OPTS:-"-B -V"}

current_version=`mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec 2>/dev/null`
dist_jar="$dist/target/ffwd-agent-${current_version}.jar"

CLASSPATH="$dist_jar"

if [[ $1 == '-debug' ]]; then
    JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=y"
    JVM_OPTS="$JVM_OPTS -Dloglevel=TRACE"
    shift
fi

if [[ -d $dist ]]; then
    if [[ ! -f $dist_jar ]]; then
        (cd $root && $MVN $MVN_OPTS clean package)
    fi

    if [[ ! -f $dist_jar ]]; then
        echo "No such jar: $dist_jar" 1>&2
        exit 1
    fi
fi

exec java -cp "$CLASSPATH" $JVM_OPTS com.spotify.ffwd.FastForwardAgent "$@"
