#!/usr/bin/env python
# Check that all files has a license header.
#
# Modifies the file to have the specified license header if it does not exist.
import sys
import os

LICENSE_PATH = "tools/license.header"


def read_header():
    lines = []
    lines += ['/**']

    with open(LICENSE_PATH) as header:
        for line in header:
            lines += [' *' + line.rstrip()]

    lines += [' **/']
    return lines


def check_action(args):
    target = args[0]

    with open(target) as f:
        file_lines = (line.rstrip() for line in f)

        for line, (head, source) in enumerate(zip(read_header(), file_lines)):

            if head == source:
                continue

            print "line #{}: {}: does not match".format(line + 1, target)
            print "expected: {}".format(head)
            print "     was: {}".format(source)
            return 1

    return 0


def patch_action(args):
    target = args[0]
    tmp_path = "{}.tmp".format(target)
    source_lines = []

    with open(tmp_path, 'w') as target_f:
        with open(target, 'r') as source_f:
            for source_line in source_f:
                if source_line.startswith('package'):
                    source_lines.append(source_line)
                    break

            for source_line in source_f:
                source_lines.append(source_line)

            for header_line in read_header():
                target_f.write(header_line + '\n')

            for line in source_lines:
                target_f.write(line)

    os.rename(tmp_path, target)
    return 0


ACTIONS = dict(
    check=check_action,
    patch=patch_action
)


def entry(args):
    action = args[0]
    return ACTIONS.get(action)(args[1:])


if __name__ == "__main__":
    sys.exit(entry(sys.argv[1:]))
